config/routes.rb
ContactManager::Application.routes.draw do

  root to: 'site#index'
  resources :companies

  resources :email_addresses, :except => [:index, :show]

  resources :phone_numbers, :except => [:index, :show]

  resources :people

  get '/auth/:provider/callback' => 'sessions#create'
  match '/login' => redirect("/auth/twitter"), as: :login
  delete '/logout' => "sessions#destroy", as: :logout



end

app/models/person.rb
class Person < ActiveRecord::Base
  attr_accessible :first_name, :last_name, :user_id
  validates :first_name, :last_name, presence: true

  include Contact

  def to_s
    "#{last_name}, #{first_name}"
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_filter :find_resource, except: [:index, :new, :create]
  # GET /people
  # GET /people.json
  def index
    @people = current_user.people

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @people }
    end
  end

  # GET /people/1
  # GET /people/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/new
  # GET /people/new.json
  def new
    @person = Person.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(params[:person])

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render json: @person, status: :created, location: @person }
      else
        format.html { render action: "new" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /people/1
  # PUT /people/1.json
  def update

    respond_to do |format|
      if @person.update_attributes(params[:person])
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy

    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :no_content }
    end
  end

end

app/views/people/_form.html.haml
= form_for(@person) do |f|
  - if @person.errors.any?
    #error_explanation
      %h2
        = pluralize(@person.errors.count, "error")
        prohibited this person from being saved:
      %ul
        - @person.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :first_name
    %br/
    = f.text_field :first_name
  .field
    = f.label :last_name
    %br/
    = f.text_field :last_name
  .actions
    = f.submit

app/views/people/edit.html.haml
%h1
  Editing #{@person}
= render 'form'
%ul.actions
  %li
    = link_to 'Show', @person
  %li
    = link_to 'Back', people_path

app/views/people/index.html.haml
%h1 Listing people
%table
  %tr
    %th First name
    %th Last name
    %th
    %th
    %th
  - @people.each do |person|
    %tr
      %td
        = person
      %td
        %ul.actions
          %li
            = link_to 'Show', person
          %li
            = link_to 'Edit', edit_person_path(person)
          %li
            = link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Person', new_person_path, id: 'new_person'

app/views/people/new.html.haml
%h1 New person
= render 'form'
= link_to 'Back', people_path

app/views/people/show.html.haml
.person
  %p#notice= notice
  %h1= @person
  = render 'phone_numbers/phone_numbers', :phone_numbers => @person.phone_numbers
  = render 'email_addresses/email_address', :email_addresses => @person.email_addresses
  %ul.actions
    %li
      = link_to 'Add phone number', new_phone_number_path(contact_id: @person.id, contact_type: 'Person')
    %li
      = link_to 'Add email address', new_email_address_path(contact_id: @person.id, contact_type: 'Person')
    %li
      = link_to 'Edit', edit_person_path(@person)
    %li
      = link_to 'Back', people_path