config/routes.rb
ContactManager::Application.routes.draw do

  root to: 'site#index'
  resources :companies

  resources :email_addresses, :except => [:index, :show]

  resources :phone_numbers, :except => [:index, :show]

  resources :people

  get '/auth/:provider/callback' => 'sessions#create'
  match '/login' => redirect("/auth/twitter"), as: :login
  delete '/logout' => "sessions#destroy", as: :logout



end

app/models/phone_number.rb
class PhoneNumber < ActiveRecord::Base
  attr_accessible :number, :contact_id, :contact_type
  validates :number, :contact_id, presence: true
  belongs_to :person
  belongs_to :company
  belongs_to :contact, polymorphic: true
end

app/controllers/phone_numbers_controller.rb
class PhoneNumbersController < ApplicationController
  before_filter :find_resource, only: [:edit, :update, :destroy]
  # GET /phone_numbers/new
  # GET /phone_numbers/new.json
  def new
    @phone_number = PhoneNumber.new(contact_id: params[:contact_id], contact_type: params[:contact_type])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @phone_number }
    end
  end

  # GET /phone_numbers/1/edit
  def edit
  end

  # POST /phone_numbers
  # POST /phone_numbers.json
  def create
    @phone_number = PhoneNumber.new(params[:phone_number])

    respond_to do |format|
      if @phone_number.save
        format.html { redirect_to @phone_number.contact, notice: 'Phone number was successfully created.' }
        format.json { render json: @phone_number, status: :created, location: @phone_number }
      else
        format.html { render action: "new" }
        format.json { render json: @phone_number.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /phone_numbers/1
  # PUT /phone_numbers/1.json
  def update
    respond_to do |format|
      if @phone_number.update_attributes(params[:phone_number])
        format.html { redirect_to @phone_number.contact, notice: 'Phone number was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @phone_number.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phone_numbers/1
  # DELETE /phone_numbers/1.json
  def destroy
    @phone_number.destroy

    respond_to do |format|
      format.html { redirect_to @phone_number.contact }
      format.json { head :no_content }
    end
  end

end

app/views/phone_numbers/_form.html.haml
= form_for(@phone_number) do |f|
  - if @phone_number.errors.any?
    .alert.alert-danger
      = pluralize(@phone_number.errors.count, "error")
      prohibited this phone_number from being saved:
      %ul
        - @phone_number.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label :number
    %br/
    = f.text_field :number

    = f.hidden_field :contact_id
    = f.hidden_field :contact_type
  .form-group.pull-right
    = f.submit class: 'btn btn-success'

app/views/phone_numbers/_phone_numbers.html.haml
%h5 Phone Numbers:
- phone_numbers.each do |phone|
  %li
    = phone.number
    = link_to('edit', edit_phone_number_path(phone))
    | #{link_to('delete', phone_number_path(phone), method: :delete)}

app/views/phone_numbers/edit.html.haml
%h1= "Editing phone number for #{@phone_number.contact}"
= render 'form'
= link_to 'Show', @phone_number

= link_to 'Back', @phone_number.contact, class: 'btn btn-default'

app/views/phone_numbers/new.html.haml
%h1
  = "New Phone Number for #{@phone_number.contact}"
= render 'form'
= link_to 'Back', @phone_number.contact, class: 'btn btn-default'