config/routes.rb
ContactManager::Application.routes.draw do

  root to: 'site#index'
  resources :companies

  resources :email_addresses, :except => [:index, :show]

  resources :phone_numbers, :except => [:index, :show]

  resources :people

  get '/auth/:provider/callback' => 'sessions#create'
  match '/login' => redirect("/auth/twitter"), as: :login
  delete '/logout' => "sessions#destroy", as: :logout



end

app/models/company.rb
class Company < ActiveRecord::Base
  attr_accessible :name, :user_id
  validates :name, presence: true
  include Contact

  def to_s
    "#{name}"
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_filter :find_resource, except: [:index, :new, :create]
  # GET /companies
  # GET /companies.json
  def index
    @companies = current_user.companies

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @companies }
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/new
  # GET /companies/new.json
  def new
    @company = Company.new(user_id: session[:user_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(params[:company])

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render json: @company, status: :created, location: @company }
      else
        format.html { render action: "new" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /companies/1
  # PUT /companies/1.json
  def update

    respond_to do |format|
      if @company.update_attributes(params[:company])
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy

    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end

  private

    def lookup_company
      @company = current_user.people.find(params[:id])
    end

end

app/views/companies/_form.html.haml
= form_for(@company) do |f|
  - if @company.errors.any?
    .col-span-4
      %h2
        = pluralize(@company.errors.count, "error")
        prohibited this company from being saved:
      %ul
        - @company.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.hidden_field :user_id
  .form-group.pull-right
    = f.submit "Create Company", class: 'btn btn-success'

app/views/companies/_show.html.haml
.panel.panel-primary
  .panel-heading.text-center Companies

  %table.table
    %tr
      %th Name
      %th.pull-right Actions

    - current_user.companies.each do |company|
      %tr
        %td= company
        %td
          .btn-group.pull-right
            = link_to 'Show', company, class: 'btn btn-success btn-sm'
            = link_to 'Edit', edit_company_path(company), class: 'btn btn-default btn-sm'
            = link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm'

  %br

app/views/companies/edit.html.haml
%h3.text-center
  Editing #{@company}

= render 'form'

.btn-group
  = link_to 'Show', @company, class: 'btn btn-default'
  = link_to 'Back', root_path, class: 'btn btn-default'

app/views/companies/index.html.haml
%h3.text-center Listing companies

%table.table.table-condensed
  %tr
    %th Name
    %th

- @companies.each do |company|
  %tr
    %td= company
    %td
      %ul.actions
        %li= link_to 'Show', company
        %li= link_to 'Edit', edit_company_path(company)
        %li= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Company', new_company_path, id: 'new_company'

app/views/companies/new.html.haml
%h3.text-center New company
= render 'form'

= link_to 'Back', companies_path, class: 'btn btn-default'

app/views/companies/show.html.erb
<div class="company">
  <h3 class='text-center'><%= @company %></h3>
  <p id='notice'>
    <%= notice %>
  </p>

  <%= render 'phone_numbers/phone_numbers', phone_numbers: @company.phone_numbers %>
  <%= render 'email_addresses/email_address', email_addresses: @company.email_addresses %>
  <br />

  <div class="btn-group pull-right">
    <button type='button' class='btn btn-success dropdown-toggle' data-toggle="dropdown">
      Add <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" role="menu">
      <li><%= link_to 'Phone Number', new_phone_number_path(contact_id: @company.id, contact_type: 'Company') %></li>
      <li><%= link_to 'Email Address', new_email_address_path(contact_id: @company.id, contact_type: 'Company') %></li>
    </ul>
  </div>

  <div class="btn-group pull-left">
    <%= link_to 'Edit', edit_company_path(@company), class: 'btn btn-default' %>
    <%= link_to 'Back', companies_path, class: 'btn btn-default' %>
  </div>
</div>

app/views/companies/show.html.haml
.company
  %h3.text-center= @company
  %p#notice= notice
  = render 'phone_numbers/phone_numbers', :phone_numbers => @company.phone_numbers
  = render 'email_addresses/email_address', :email_addresses => @company.email_addresses
  %br
.btn-group.pull-right
  %button.btn.btn-default.dropdown-toggle
    Add
  %ul.dropdown-menu
    %li= link_to 'Add phone number', new_phone_number_path(contact_id: @company.id, contact_type: 'Company')
    %li= link_to 'Add email address', new_email_address_path(contact_id: @company.id, contact_type: 'Company')

.btn-group.pull-left
  = link_to 'Edit', edit_company_path(@company), class: 'btn btn-default'
  = link_to 'Back', companies_path, class: 'btn btn-default'