config/routes.rb
ContactManager::Application.routes.draw do

  root to: 'site#index'
  resources :companies

  resources :email_addresses, :except => [:index, :show]

  resources :phone_numbers, :except => [:index, :show]

  resources :people

  get '/auth/:provider/callback' => 'sessions#create'
  match '/login' => redirect("/auth/twitter"), as: :login
  delete '/logout' => "sessions#destroy", as: :logout



end

app/controllers/email_addresses_controller.rb
class EmailAddressesController < ApplicationController
  before_filter :find_resource, only: [:edit, :update, :destroy]
  # GET /email_addresses/new
  # GET /email_addresses/new.json
  def new
    @email_address = EmailAddress.new(contact_id: params[:contact_id], contact_type: params[:contact_type])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @email_address }
    end
  end

  # GET /email_addresses/1/edit
  def edit
  end

  # POST /email_addresses
  # POST /email_addresses.json
  def create
    @email_address = EmailAddress.new(params[:email_address])

    respond_to do |format|
      if @email_address.save
        format.html { redirect_to @email_address.contact, notice: 'Email address was successfully created.' }
        format.json { render json: @email_address, status: :created, location: @email_address }
      else
        format.html { render action: "new" }
        format.json { render json: @email_address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /email_addresses/1
  # PUT /email_addresses/1.json
  def update

    respond_to do |format|
      if @email_address.update_attributes(params[:email_address])
        format.html { redirect_to @email_address.contact, notice: 'Email address was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @email_address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /email_addresses/1
  # DELETE /email_addresses/1.json
  def destroy
    @email_address.destroy

    respond_to do |format|
      format.html { redirect_to @email_address.contact }
      format.json { head :no_content }
    end
  end

end

app/views/email_addresses/_email_address.html.haml
%p
%h5 Email Addresses:
- email_addresses.each do |email_address|
  %li
    = email_address.address
    = link_to('edit', edit_email_address_path(email_address))
    | #{link_to('delete', email_address_path(email_address), method: :delete)}

app/views/email_addresses/_form.html.haml
= form_for(@email_address) do |f|
  - if @email_address.errors.any?
    .alert.alert-danger
      = pluralize(@email_address.errors.count, "error")
      prohibited this email_address from being saved:

      - @email_address.errors.full_messages.each do |msg|
        %li= msg
  .form-group
    = f.label :address
    %br/
    = f.text_field :address, class: 'form-control'

    = f.hidden_field :contact_id, class: 'form-control'
    = f.hidden_field :contact_type
  .form-group.pull-right
    = f.submit class: 'btn btn-success'

app/views/email_addresses/edit.html.haml
%h5= "Editing email address for #{@email_address.contact}"
= render 'form'
= link_to 'Show', @email_address
= link_to 'Back', @email_address.contact

app/views/email_addresses/new.html.haml
%h5= "New email address for #{@email_address.contact}"
= render 'form'
= link_to 'Back', @email_address.contact